In [1]:
# Check R version
R.version.string

[1] "R version 4.6.1 (2026-06-24)"

In [2]:
install.packages(c(
  "dplyr",
  "ggplot2",
  "tidyr",
  "readr",
  "readxl",
  "writexl",
  "data.table"
))

Installing packages into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

In [3]:
library(dplyr)
library(ggplot2)
library(tidyr)
library(readr)
library(readxl)
library(writexl)
library(data.table)

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union



Attaching package: ‘data.table’


The following objects are masked from ‘package:dplyr’:

    between, first, last


The following object is masked from ‘package:base’:

    %notin%

In [4]:
# Check R version
R.version.string

# Test calculation
a <- 10
b <- 20

a + b

[1] "R version 4.6.1 (2026-06-24)"

[1] 30

In [5]:
# Install required packages
install.packages(c(
  "tidyverse",
  "jsonlite",
  "readxl",
  "writexl",
  "RSQLite",
  "DBI"
))

Installing packages into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

In [6]:
library(tidyverse)
library(jsonlite)
library(readxl)
library(writexl)
library(RSQLite)
library(DBI)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ lubridate 1.9.5     ✔ tibble    3.3.1
✔ purrr     1.2.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ data.table::between() masks dplyr::between()
✖ dplyr::filter()       masks stats::filter()
✖ data.table::first()   masks dplyr::first()
✖ lubridate::hour()     masks data.table::hour()
✖ lubridate::isoweek()  masks data.table::isoweek()
✖ lubridate::isoyear()  masks data.table::isoyear()
✖ dplyr::lag()          masks stats::lag()
✖ data.table::last()    masks dplyr::last()
✖ lubridate::mday()     masks data.table::mday()
✖ lubridate::minute()   masks data.table::minute()
✖ lubridate::month()    masks data.table::month()
✖ lubridate::quarter()  masks data.table::quarter()
✖ lubridate::second()   masks data.table::second()
✖ purrr::transpose()    masks data.table::transpose()
✖ lubridate::wday()     masks data.table::wday()
✖ lubridate::week()     masks data.table::week()
✖ lubridate::yday()     masks data.table::yday()
✖ lubridate::year()     masks data.table::year()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Attaching package: ‘jsonlite’


The following object is masked from ‘package:purrr’:

    flatten

In [7]:
# Create transactions dataset

transactions <- data.frame(
  InvoiceNo = c(
    "10001","10002","10003","10004","10005",
    "10006","10007","10008","10009","10010",
    "10011","10012","10013","10014","10015",
    "10016","10017","10018","10019","10020"
  ),

  StockCode = c(
    "P001","P002","P003","P001","P004",
    "P005","P002","P006","P003","P007",
    "P001","P004","P005","P002","P006",
    "P007","P003","P004","P001","P005"
  ),

  CustomerID = c(
    "C001","C002","C003","C004","C005",
    "C001","C006","C007","C002","C008",
    "C003","C009","C010","C004","C005",
    "C006","C007","C008","C001","C010"
  ),

  Quantity = c(
    5,3,2,4,6,
    10,5,3,7,2,
    8,4,6,5,3,
    4,9,2,7,5
  ),

  InvoiceDate = c(
    "2026-01-05","2026-01-06","2026-01-07","2026-01-08",
    "2026-01-09","2026-01-10","2026-01-11","2026-01-12",
    "2026-01-13","2026-01-14","2026-01-15","2026-01-16",
    "2026-01-17","2026-01-18","2026-01-19","2026-01-20",
    "2026-01-21","2026-01-22","2026-01-23","2026-01-24"
  )
)

# Save as CSV
write.csv(
  transactions,
  "transactions.csv",
  row.names = FALSE
)

# Display dataset
transactions

   InvoiceNo StockCode CustomerID Quantity InvoiceDate
1  10001     P001      C001        5       2026-01-05
2  10002     P002      C002        3       2026-01-06
3  10003     P003      C003        2       2026-01-07
4  10004     P001      C004        4       2026-01-08
5  10005     P004      C005        6       2026-01-09
6  10006     P005      C001       10       2026-01-10
7  10007     P002      C006        5       2026-01-11
8  10008     P006      C007        3       2026-01-12
9  10009     P003      C002        7       2026-01-13
10 10010     P007      C008        2       2026-01-14
11 10011     P001      C003        8       2026-01-15
12 10012     P004      C009        4       2026-01-16
13 10013     P005      C010        6       2026-01-17
14 10014     P002      C004        5       2026-01-18
15 10015     P006      C005        3       2026-01-19
16 10016     P007      C006        4       2026-01-20
17 10017     P003      C007        9       2026-01-21
18 10018     P004      C008        2       2026-01-22
19 10019     P001      C001        7       2026-01-23
20 10020     P005      C010        5       2026-01-24

In [8]:
# Create products dataset

products <- data.frame(
  StockCode = c(
    "P001","P002","P003","P004",
    "P005","P006","P007"
  ),

  Description = c(
    "Wireless Mouse",
    "Keyboard",
    "USB Cable",
    "Laptop Stand",
    "Headphones",
    "Webcam",
    "Power Bank"
  ),

  UnitPrice = c(
    800,
    1200,
    500,
    1500,
    2000,
    2500,
    1800
  )
)

# Convert to JSON
products_json <- toJSON(
  products,
  pretty = TRUE
)

# Save JSON file
write(
  products_json,
  "products.json"
)

# Display
products

  StockCode Description    UnitPrice
1 P001      Wireless Mouse  800
2 P002      Keyboard       1200
3 P003      USB Cable       500
4 P004      Laptop Stand   1500
5 P005      Headphones     2000
6 P006      Webcam         2500
7 P007      Power Bank     1800

In [9]:
# Create customers dataset

customers <- data.frame(
  CustomerID = c(
    "C001","C002","C003","C004","C005",
    "C006","C007","C008","C009","C010"
  ),

  Country = c(
    "India",
    "USA",
    "UK",
    "India",
    "Germany",
    "USA",
    "UK",
    "France",
    "Germany",
    "India"
  )
)

# Save as Excel file
write_xlsx(
  customers,
  "customers.xlsx"
)

# Display
customers

   CustomerID Country
1  C001       India
2  C002       USA
3  C003       UK
4  C004       India
5  C005       Germany
6  C006       USA
7  C007       UK
8  C008       France
9  C009       Germany
10 C010       India

In [10]:
# Check files created

list.files()

[1] "customers.xlsx"   "products.json"    "sample_data"      "transactions.csv"

In [11]:
file.exists("transactions.csv")
file.exists("products.json")
file.exists("customers.xlsx")

[1] TRUE

[1] TRUE

[1] TRUE

In [12]:
# Create transactions.csv

transactions <- data.frame(
  InvoiceNo = c("10001", "10002", "10003", "10004", "10005"),
  StockCode = c("P001", "P002", "P003", "P001", "P004"),
  CustomerID = c("C001", "C002", "C003", "C001", "C004"),
  Quantity = c(5, 3, 2, 4, 6),
  InvoiceDate = c(
    "2026-01-05",
    "2026-01-06",
    "2026-01-07",
    "2026-01-08",
    "2026-01-09"
  )
)

write.csv(
  transactions,
  "transactions.csv",
  row.names = FALSE
)

# Display the data
transactions

  InvoiceNo StockCode CustomerID Quantity InvoiceDate
1 10001     P001      C001       5        2026-01-05
2 10002     P002      C002       3        2026-01-06
3 10003     P003      C003       2        2026-01-07
4 10004     P001      C001       4        2026-01-08
5 10005     P004      C004       6        2026-01-09

In [13]:
# Create products dataset

products <- data.frame(
  StockCode = c("P001", "P002", "P003", "P004"),
  Description = c(
    "Wireless Mouse",
    "Keyboard",
    "USB Cable",
    "Laptop Stand"
  ),
  UnitPrice = c(800, 1200, 500, 1500)
)

# Convert data frame to JSON
products_json <- toJSON(products, pretty = TRUE)

# Save JSON file
write(products_json, "products.json")

# Display products
products

  StockCode Description    UnitPrice
1 P001      Wireless Mouse  800
2 P002      Keyboard       1200
3 P003      USB Cable       500
4 P004      Laptop Stand   1500

In [14]:
library(jsonlite)

In [15]:
file.exists("products.json")

[1] TRUE

In [16]:
# Create customers dataset

customers <- data.frame(
  CustomerID = c("C001", "C002", "C003", "C004"),
  Country = c(
    "India",
    "USA",
    "UK",
    "Germany"
  )
)

# Save as Excel file
write_xlsx(
  customers,
  "customers.xlsx"
)

# Display customers
customers

  CustomerID Country
1 C001       India
2 C002       USA
3 C003       UK
4 C004       Germany

In [17]:
file.exists("customers.xlsx")

[1] TRUE

In [18]:
# Import transactions CSV

transactions_data <- read.csv("transactions.csv")

# Display the data
transactions_data

  InvoiceNo StockCode CustomerID Quantity InvoiceDate
1 10001     P001      C001       5        2026-01-05
2 10002     P002      C002       3        2026-01-06
3 10003     P003      C003       2        2026-01-07
4 10004     P001      C001       4        2026-01-08
5 10005     P004      C004       6        2026-01-09

In [19]:
str(transactions_data)

'data.frame':	5 obs. of  5 variables:
 $ InvoiceNo  : int  10001 10002 10003 10004 10005
 $ StockCode  : chr  "P001" "P002" "P003" "P001" ...
 $ CustomerID : chr  "C001" "C002" "C003" "C001" ...
 $ Quantity   : int  5 3 2 4 6
 $ InvoiceDate: chr  "2026-01-05" "2026-01-06" "2026-01-07" "2026-01-08" ...

In [20]:
# Import products JSON

products_data <- fromJSON("products.json")

# Display the data
products_data

  StockCode Description    UnitPrice
1 P001      Wireless Mouse  800
2 P002      Keyboard       1200
3 P003      USB Cable       500
4 P004      Laptop Stand   1500

In [21]:
str(products_data)

'data.frame':	4 obs. of  3 variables:
 $ StockCode  : chr  "P001" "P002" "P003" "P004"
 $ Description: chr  "Wireless Mouse" "Keyboard" "USB Cable" "Laptop Stand"
 $ UnitPrice  : int  800 1200 500 1500

In [22]:
# Import customers Excel file

customers_data <- read_excel("customers.xlsx")

# Display the data
customers_data

  CustomerID Country
1 C001       India
2 C002       USA
3 C003       UK
4 C004       Germany

In [23]:
str(customers_data)

tibble [4 × 2] (S3: tbl_df/tbl/data.frame)
 $ CustomerID: chr [1:4] "C001" "C002" "C003" "C004"
 $ Country   : chr [1:4] "India" "USA" "UK" "Germany"

In [24]:
# Check dimensions

dim(transactions_data)
dim(products_data)
dim(customers_data)

[1] 5 5

[1] 4 3

[1] 4 2

In [25]:
# Check missing values in transactions

colSums(is.na(transactions_data))

  InvoiceNo   StockCode  CustomerID    Quantity InvoiceDate
          0           0           0           0           0

In [26]:
# Check missing values in products

colSums(is.na(products_data))

  StockCode Description   UnitPrice
          0           0           0

In [27]:
# Check missing values in customers

colSums(is.na(customers_data))

CustomerID    Country
         0          0

In [28]:
# Check duplicate records in transactions

sum(duplicated(transactions_data))

[1] 0

In [29]:
# Check duplicate records in products

sum(duplicated(products_data))

[1] 0

In [30]:
# Check duplicate records in customers

sum(duplicated(customers_data))

[1] 0

In [31]:
# Remove duplicate records

transactions_data <- transactions_data %>%
  distinct()

products_data <- products_data %>%
  distinct()

customers_data <- customers_data %>%
  distinct()

In [32]:
# Check quantity values

transactions_data$Quantity

[1] 5 3 2 4 6

In [33]:
# Count invalid quantities

sum(transactions_data$Quantity <= 0)

[1] 0

In [34]:
# Remove zero and negative quantities

transactions_data <- transactions_data %>%
  filter(Quantity > 0)

In [35]:
# Check number of transactions after cleaning

nrow(transactions_data)

[1] 5

In [36]:
# Check product prices

products_data$UnitPrice

[1]  800 1200  500 1500

In [37]:
# Count invalid prices

sum(products_data$UnitPrice <= 0)

[1] 0

In [38]:
# Remove zero and negative prices

products_data <- products_data %>%
  filter(UnitPrice > 0)

In [39]:
# Check number of products after cleaning

nrow(products_data)

[1] 4

In [40]:
# Combine transactions with product prices

transactions_clean <- transactions_data %>%
  left_join(
    products_data,
    by = "StockCode"
  )

# Display result
transactions_clean

  InvoiceNo StockCode CustomerID Quantity InvoiceDate Description    UnitPrice
1 10001     P001      C001       5        2026-01-05  Wireless Mouse  800
2 10002     P002      C002       3        2026-01-06  Keyboard       1200
3 10003     P003      C003       2        2026-01-07  USB Cable       500
4 10004     P001      C001       4        2026-01-08  Wireless Mouse  800
5 10005     P004      C004       6        2026-01-09  Laptop Stand   1500

In [41]:
# Calculate Revenue

transactions_clean <- transactions_clean %>%
  mutate(
    Revenue = Quantity * UnitPrice
  )

# Display final cleaned transactions
transactions_clean

  InvoiceNo StockCode CustomerID Quantity InvoiceDate Description    UnitPrice
1 10001     P001      C001       5        2026-01-05  Wireless Mouse  800
2 10002     P002      C002       3        2026-01-06  Keyboard       1200
3 10003     P003      C003       2        2026-01-07  USB Cable       500
4 10004     P001      C001       4        2026-01-08  Wireless Mouse  800
5 10005     P004      C004       6        2026-01-09  Laptop Stand   1500
  Revenue
1 4000
2 3600
3 1000
4 3200
5 9000

In [42]:
# View revenue

transactions_clean %>%
  select(
    InvoiceNo,
    StockCode,
    Quantity,
    UnitPrice,
    Revenue
  )

  InvoiceNo StockCode Quantity UnitPrice Revenue
1 10001     P001      5         800      4000
2 10002     P002      3        1200      3600
3 10003     P003      2         500      1000
4 10004     P001      4         800      3200
5 10005     P004      6        1500      9000

In [43]:
# Integrate transaction and customer data

final_data <- transactions_clean %>%
  left_join(
    customers_data,
    by = "CustomerID"
  )

# Display integrated dataset
final_data

  InvoiceNo StockCode CustomerID Quantity InvoiceDate Description    UnitPrice
1 10001     P001      C001       5        2026-01-05  Wireless Mouse  800
2 10002     P002      C002       3        2026-01-06  Keyboard       1200
3 10003     P003      C003       2        2026-01-07  USB Cable       500
4 10004     P001      C001       4        2026-01-08  Wireless Mouse  800
5 10005     P004      C004       6        2026-01-09  Laptop Stand   1500
  Revenue Country
1 4000    India
2 3600    USA
3 1000    UK
4 3200    India
5 9000    Germany

In [44]:
# Check dimensions of final integrated dataset

dim(final_data)

[1] 5 9

In [45]:
# Number of rows and columns

nrow(final_data)
ncol(final_data)

[1] 5

[1] 9

In [46]:
# Check unmatched product records

unmatched_products <- transactions_data %>%
  anti_join(
    products_data,
    by = "StockCode"
  )

unmatched_products

     InvoiceNo StockCode CustomerID Quantity InvoiceDate

In [47]:
nrow(unmatched_products)

[1] 0

In [48]:
# Check unmatched customer records

unmatched_customers <- transactions_data %>%
  anti_join(
    customers_data,
    by = "CustomerID"
  )

unmatched_customers

     InvoiceNo StockCode CustomerID Quantity InvoiceDate

In [49]:
nrow(unmatched_customers)

[1] 0

In [50]:
# Calculate total sales revenue

total_revenue <- final_data %>%
  summarise(
    Total_Revenue = sum(Revenue)
  )

total_revenue

  Total_Revenue
1 20800

In [51]:
# Top 5 products based on revenue

top_products <- final_data %>%
  group_by(StockCode, Description) %>%
  summarise(
    Total_Revenue = sum(Revenue),
    .groups = "drop"
  ) %>%
  arrange(desc(Total_Revenue)) %>%
  slice_head(n = 5)

top_products

  StockCode Description    Total_Revenue
1 P004      Laptop Stand   9000
2 P001      Wireless Mouse 7200
3 P002      Keyboard       3600
4 P003      USB Cable      1000

In [52]:
# Top 5 countries based on revenue

top_countries <- final_data %>%
  group_by(Country) %>%
  summarise(
    Total_Revenue = sum(Revenue),
    .groups = "drop"
  ) %>%
  arrange(desc(Total_Revenue)) %>%
  slice_head(n = 5)

top_countries

  Country Total_Revenue
1 Germany 9000
2 India   7200
3 USA     3600
4 UK      1000

In [53]:
# Top 5 customers based on total purchase value

top_customers <- final_data %>%
  group_by(CustomerID, Country) %>%
  summarise(
    Total_Purchase = sum(Revenue),
    .groups = "drop"
  ) %>%
  arrange(desc(Total_Purchase)) %>%
  slice_head(n = 5)

top_customers

  CustomerID Country Total_Purchase
1 C004       Germany 9000
2 C001       India   7200
3 C002       USA     3600
4 C003       UK      1000

In [54]:
# Calculate purchase value for every customer

customer_value <- final_data %>%
  group_by(CustomerID, Country) %>%
  summarise(
    Total_Purchase = sum(Revenue),
    .groups = "drop"
  )

customer_value

  CustomerID Country Total_Purchase
1 C001       India   7200
2 C002       USA     3600
3 C003       UK      1000
4 C004       Germany 9000

In [55]:
# Classify customers based on purchase value

customer_value <- customer_value %>%
  mutate(
    Customer_Category = case_when(
      Total_Purchase < 3000 ~ "Low Value",
      Total_Purchase < 6000 ~ "Medium Value",
      Total_Purchase < 10000 ~ "High Value",
      Total_Purchase >= 10000 ~ "Premium"
    )
  )

# Display customer classification

customer_value

  CustomerID Country Total_Purchase Customer_Category
1 C001       India   7200           High Value
2 C002       USA     3600           Medium Value
3 C003       UK      1000           Low Value
4 C004       Germany 9000           High Value

In [56]:
condition 1 → Low Value
condition 2 → Medium Value
condition 3 → High Value
condition 4 → Premium

ERROR: Error in parse(text = input): <text>:1:11: unexpected numeric constant
1: condition 1
              ^

In [57]:
# Classify customers based on purchase value

customer_value <- customer_value %>%
  mutate(
    Customer_Category = case_when(
      Total_Purchase < 3000 ~ "Low Value",
      Total_Purchase < 6000 ~ "Medium Value",
      Total_Purchase < 10000 ~ "High Value",
      Total_Purchase >= 10000 ~ "Premium"
    )
  )

# Display customer classification

customer_value

  CustomerID Country Total_Purchase Customer_Category
1 C001       India   7200           High Value
2 C002       USA     3600           Medium Value
3 C003       UK      1000           Low Value
4 C004       Germany 9000           High Value

In [58]:
condition 1 → Low Value
condition 2 → Medium Value
condition 3 → High Value
condition 4 → Premium

ERROR: Error in parse(text = input): <text>:1:11: unexpected numeric constant
1: condition 1
              ^

In [59]:
condition 1 → Low Value

ERROR: Error in parse(text = input): <text>:1:11: unexpected numeric constant
1: condition 1
              ^

In [60]:
# Classify customers based on purchase value

customer_value <- customer_value %>%
  mutate(
    Customer_Category = case_when(
      Total_Purchase < 3000 ~ "Low Value",
      Total_Purchase < 6000 ~ "Medium Value",
      Total_Purchase < 10000 ~ "High Value",
      Total_Purchase >= 10000 ~ "Premium"
    )
  )

# Display the result
customer_value

  CustomerID Country Total_Purchase Customer_Category
1 C001       India   7200           High Value
2 C002       USA     3600           Medium Value
3 C003       UK      1000           Low Value
4 C004       Germany 9000           High Value

In [61]:
# Count customers in each category

customer_value %>%
  count(Customer_Category)

  Customer_Category n
1 High Value        2
2 Low Value         1
3 Medium Value      1

In [62]:
# Highest-performing market

high_performing_market <- top_countries %>%
  arrange(desc(Total_Revenue)) %>%
  slice(1)

high_performing_market

  Country Total_Revenue
1 Germany 9000

In [63]:
# Lowest-performing market

underperforming_market <- top_countries %>%
  arrange(Total_Revenue) %>%
  slice(1)

underperforming_market

  Country Total_Revenue
1 UK      1000

In [64]:
# Display market performance

cat("High-performing market:\n")
print(high_performing_market)

cat("\nUnderperforming market:\n")
print(underperforming_market)

High-performing market:
# A tibble: 1 × 2
  Country Total_Revenue
  <chr>           <int>
1 Germany          9000

Underperforming market:
# A tibble: 1 × 2
  Country Total_Revenue
  <chr>           <int>
1 UK               1000

In [65]:
# Create SQLite database

con <- dbConnect(
  SQLite(),
  "retail_sales.db"
)

# Check database connection
con

<SQLiteConnection>
  Path: retail_sales.db
  Extensions: TRUE

In [66]:
# Export final integrated data to SQLite

dbWriteTable(
  con,
  "retail_sales",
  final_data,
  overwrite = TRUE
)

print("Data successfully stored in retail_sales table")

[1] "Data successfully stored in retail_sales table"

In [67]:
# List tables in database

dbListTables(con)

[1] "retail_sales"

In [68]:
# Display data stored in SQLite

dbReadTable(
  con,
  "retail_sales"
)

  InvoiceNo StockCode CustomerID Quantity InvoiceDate Description    UnitPrice
1 10001     P001      C001       5        2026-01-05  Wireless Mouse  800
2 10002     P002      C002       3        2026-01-06  Keyboard       1200
3 10003     P003      C003       2        2026-01-07  USB Cable       500
4 10004     P001      C001       4        2026-01-08  Wireless Mouse  800
5 10005     P004      C004       6        2026-01-09  Laptop Stand   1500
  Revenue Country
1 4000    India
2 3600    USA
3 1000    UK
4 3200    India
5 9000    Germany

In [69]:
# SQL Query 1: Top 5 customers by revenue

query1 <- "
SELECT
    CustomerID,
    Country,
    SUM(Revenue) AS Total_Revenue
FROM retail_sales
GROUP BY CustomerID, Country
ORDER BY Total_Revenue DESC
LIMIT 5;
"

top_5_customers_sql <- dbGetQuery(
  con,
  query1
)

top_5_customers_sql

  CustomerID Country Total_Revenue
1 C004       Germany 9000
2 C001       India   7200
3 C002       USA     3600
4 C003       UK      1000

In [71]:
# SQL Query 2: Total revenue by country

query2 <- "
SELECT
    Country,
    SUM(Revenue) AS Total_Revenue
FROM retail_sales
GROUP BY Country
ORDER BY Total_Revenue DESC;
"

revenue_by_country_sql <- dbGetQuery(
  con,
  query2
)

revenue_by_country_sql

  Country Total_Revenue
1 Germany 9000
2 India   7200
3 USA     3600
4 UK      1000

In [72]:
# Close SQLite connection

dbDisconnect(con)

print("SQLite database connection closed")

[1] "SQLite database connection closed"

In [73]:
# 1. Total revenue
total_revenue

# 2. Top performing country
top_country <- revenue_by_country_sql %>%
  arrange(desc(Total_Revenue)) %>%
  slice(1)

top_country

# 3. Top customer
top_customer <- top_5_customers_sql %>%
  arrange(desc(Total_Revenue)) %>%
  slice(1)

top_customer

  Total_Revenue
1 20800

  Country Total_Revenue
1 Germany 9000

  CustomerID Country Total_Revenue
1 C004       Germany 9000

In [74]:
# Generate business insights

cat("BUSINESS INSIGHTS\n")
cat("=================\n\n")

cat(
  "1. Overall Revenue: The total revenue generated from the analyzed transactions is ",
  total_revenue$Total_Revenue,
  ".\n\n"
)

cat(
  "2. High-Performing Market: ",
  top_country$Country,
  " generated the highest revenue of ",
  top_country$Total_Revenue,
  ", making it the strongest market in the dataset.\n\n"
)

cat(
  "3. Top Customer: Customer ",
  top_customer$CustomerID,
  " from ",
  top_customer$Country,
  " generated the highest purchase value of ",
  top_customer$Total_Revenue,
  ". This customer represents an important high-value customer segment.\n"
)

BUSINESS INSIGHTS
=================

1. Overall Revenue: The total revenue generated from the analyzed transactions is  20800 .

2. High-Performing Market:  Germany  generated the highest revenue of  9000 , making it the strongest market in the dataset.

3. Top Customer: Customer  C004  from  Germany  generated the highest purchase value of  9000 . This customer represents an important high-value customer segment.

In [75]:
# Final dataset

print("Final Integrated Dataset:")
print(final_data)

cat("\nFinal Dimensions:\n")
print(dim(final_data))

cat("\nTotal Revenue:\n")
print(total_revenue)

cat("\nTop 5 Products:\n")
print(top_products)

cat("\nTop 5 Countries:\n")
print(top_countries)

cat("\nTop 5 Customers:\n")
print(top_customers)

cat("\nCustomer Classification:\n")
print(customer_value)

cat("\nRevenue by Country from SQL:\n")
print(revenue_by_country_sql)

[1] "Final Integrated Dataset:"
  InvoiceNo StockCode CustomerID Quantity InvoiceDate    Description UnitPrice
1     10001      P001       C001        5  2026-01-05 Wireless Mouse       800
2     10002      P002       C002        3  2026-01-06       Keyboard      1200
3     10003      P003       C003        2  2026-01-07      USB Cable       500
4     10004      P001       C001        4  2026-01-08 Wireless Mouse       800
5     10005      P004       C004        6  2026-01-09   Laptop Stand      1500
  Revenue Country
1    4000   India
2    3600     USA
3    1000      UK
4    3200   India
5    9000 Germany

Final Dimensions:
[1] 5 9

Total Revenue:
  Total_Revenue
1         20800

Top 5 Products:
# A tibble: 4 × 3
  StockCode Description    Total_Revenue
  <chr>     <chr>                  <int>
1 P004      Laptop Stand            9000
2 P001      Wireless Mouse          7200
3 P002      Keyboard                3600
4 P003      USB Cable               1000

Top 5 Countries:
# A tibble: 4 × 2
  Country Total_Revenue
  <chr>           <int>
1 Germany          9000
2 India            7200
3 USA              3600
4 UK               1000

Top 5 Customers:
# A tibble: 4 × 3
  CustomerID Country Total_Purchase
  <chr>      <chr>            <int>
1 C004       Germany           9000
2 C001       India             7200
3 C002       USA               3600
4 C003       UK                1000

Customer Classification:
# A tibble: 4 × 4
  CustomerID Country Total_Purchase Customer_Category
  <chr>      <chr>            <int> <chr>
1 C001       India             7200 High Value
2 C002       USA               3600 Medium Value
3 C003       UK                1000 Low Value
4 C004       Germany           9000 High Value

Revenue by Country from SQL:
  Country Total_Revenue
1 Germany          9000
2   India          7200
3     USA          3600
4      UK          1000